### ISSUE TITLE
Use lexical analysis when processing text

### ISSUE THREAD

**Issue by diemonster** [quintilesims/slackbot#56]
Several commands in slackbot could benefit from lexical analysis. For example, we should be able to easily identify nouns, verbs, subjects, etc in a given string and build logic around word tagging. It would certainly improve commands such as:
https://github.com/quintilesims/slackbot/issues/24
https://github.com/quintilesims/slackbot/issues/43

So far, the most popular Go libraries I've found for doing this sort of thing are:
https://github.com/jdkato/prose
https://github.com/james-bowman/nlp
https://github.com/advancedlogic/go-freeling

**Comment by zpatrick** [comment]
Closing this so we can move the conversation to https://github.com/quintilesims/slackbot/issues/43. 
I believe those two tickets are trying to provide the same features.
